### ISSUE TITLE
ignore some non OpenAPI files, e.g. .gitlab-ci.yml

### ISSUE THREAD

**Issue by ghost** [stoplightio/vscode-spectral#106]
**Chore summary**
ignore some non OpenAPI files, e.g. .gitlab-ci.yml

**Tasks**
- [ ] ignore some non OpenAPI files, e.g. .gitlab-ci.yml.
- [ ] ignore given non OpenAPI files, otherwise, e.g. .gitlab-ci.yml is being highlighted with errors/warnings.

**Additional context**

**Comment by oceanofmaya** [comment]
I have a similar request where in I want to ignore CloudFormation template files e.g. template.yml from being scanned or parsed by spectral. If a feature can be built to add ignorePaths to inform glob patterns the plugin would ignore, it would be really helpful.
