### ISSUE TITLE
Allow the use of remote ruleset files that are hosted on http

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/vscode-spectral#149]
**Describe the bug**
It looks like its is not possible to use custom rulesets that are hosted on HTTP such as: https://api.oneadvanced.com/rules/spectral.yaml instead of having a local rule set file.
**To Reproduce**

1. Update the VS code extension setting "Spectral Ruleset File" to be a remote ruleset
3. Open an API and create a query parameter that is not cased in camelCase

**Expected behavior**
The custom ruleset is loaded and an error is displayed. (This is what happens with the CLI today)

**Environment:**
 - Extension version: [0.2.5]
 - VS Code version: [1.6.8]
 - Operating System: [10]

**Comment by philsturgeon** [comment]
@mnaumanali94 hey can I tag you in on this one? This is a common and recommended way of distributing rulesets so if it’s not working right now we should jump on it.

**Comment by savage-alex** [comment]
Thanks @philsturgeon, im trying to avoid going down the npm route to package the rulsets which I have seen some others do :-(

**Comment by savage-alex** [comment]
Hey all, is this something you would like help with?

**Comment by philsturgeon** [comment]
The Stoplight team would always be happy to have any help with any of our open-source projects.  It often feels like people expect us to do 100% of the features/bugs/etc ourselves but that's completely undoable, so it's always fantastic when the community can pitch in to do their bit!

**Comment by NickHeap2** [comment]
@philsturgeon Have started working on this. Will put up a PR after I've firmed up the tests. 
![image](https://user-images.githubusercontent.com/42422453/185488512-14defb7f-1da5-48e1-a5c3-3a82167beefa.png)

**Comment by philsturgeon** [comment]
@NickHeap2 thanks Nick!
