### ISSUE TITLE
Version 1.1.1 not available in VS Code Marketplace

### ISSUE THREAD

**Issue by jc43081** [stoplightio/vscode-spectral#199]
**Describe the bug**
The current release of 1.1.1 is not available in the VS Code Marketplace. The last update date matches the release date of 1.1.1 (January 17, 2023), but the available version is still 1.1.0. 

**To Reproduce**
Visit the Marketplace and observe the last update date and the version - https://marketplace.visualstudio.com/items?itemName=stoplight.spectral

**Expected behavior**
Version 1.1.1 be available on the Marketplace

**Comment by mnaumanali94** [comment]
1.1.2 is now available.
