### ISSUE TITLE
Allow URI for spectral.rulesetFile configuration setting

### ISSUE THREAD

**Issue by mbenda-fds** [stoplightio/vscode-spectral#53]
**User story.**
As a software engineer, I'd like to lint using a remote ruleset file, so that my coworkers and I do not have to have local copies of the ruleset file.

**Is your feature request related to a problem?**
I'd like to have consistent OpenAPI documents throughout my organization.  In order to do this, I'd like to have one copy of the rules file that everyone can reference.  This way, if we make changes in the future to the document, everyone gets an update right away and linting works as expected. 

**Describe the solution you'd like**
I'd like to have the ability to type in a URI to the `spectral.rulesetFile` configuration setting.

**Comment by philsturgeon** [comment]
Good idea! You can do this for now via making a `.spectral.yml` which extends from a URL, and that means it'll be noticed in CI, when teammates use the CLI, etc., but this would be a useful feature too.

**Comment by mbenda-fds** [comment]
Hi @philsturgeon  - can you elaborate on how to make a .spectral.yml extend from a URL?

**Comment by philsturgeon** [comment]
Here you go! 

https://meta.stoplight.io/docs/spectral/docs/getting-started/3-rulesets.md#extending-rulesets

**Comment by mbenda-fds** [comment]
thanks @philsturgeon  - that's a workaround until we can get the URL in the configuration.

**Comment by ioggstream** [comment]
an example file:

```
echo > .spectral.yml "
extends:
- https://raw.githubusercontent.com/italia/api-oas-checker/gh-pages/spectral-full.yml
"
```

**Comment by philsturgeon** [comment]
Thanks @ioggstream, that's exactly right. This seems like its handled but let me know if there's something else!

**Comment by elqueso** [comment]
Hi @philsturgeon 
Although that solution works just fine, it doesn't solve the initial problem.  We are using vscode-spectral in an enterprise setting, with many engineers with many different repositories using it.  We'd prefer not having every engineer ensure they have a .spectral-yaml file in their local code repo that just redirects to our enterprise config file.  It'd be easier to have them just set the extension setting to the centralized location.
Please let me know what you think.
Thanks!

**Comment by philsturgeon** [comment]
If you're using Spectral in an enterprise setting you have CI/CD right? You'll need that .spectral.yml for CI/CD to be able to confirm these same rules, otherwise you're relying on every single user entering the same config into the extension which seems ... unlikely. If you commit this file, you ensure every developer _and_ CI/CD are using it everywhere.

**Comment by ioggstream** [comment]
@elqueso whether it's .spectral.yml or a vscode configuration file, or a vscode configurator, you need something in the repo:

1- you can enforce its presence via a repository scraper (we do something similar to index free software in the Italian Software Reuse Catalogue);
2- you can add to your `.github` repository, so every new repo will inherit it;

@philsturgeon can I add the example to this repo=

**Comment by philsturgeon** [comment]
Please do!
