### ISSUE TITLE
Bump spectral to 5.8.0

### ISSUE THREAD

**Issue by ioggstream** [stoplightio/vscode-spectral#68]
**Chore summary**
Upgrade spectral to 5.8.0

**Additional context**
It is needed to support new spectral function

cc: @emiliosp

**Comment by ioggstream** [comment]
@philsturgeon if we provide a PR for this issue, will you merge it?

**Comment by philsturgeon** [comment]
I was just about to then got pulled into some meetings. If you can do that I’ll be happy to merge. 

--
Phil Sturgeon
DevRel @ Stoplight.io

**Comment by emilioSp** [comment]
@philsturgeon I've created a PR https://github.com/stoplightio/vscode-spectral/pull/69
