### ISSUE TITLE
Release a new version on marketplace, featuring Spectral 5.8

### ISSUE THREAD

**Issue by ioggstream** [stoplightio/vscode-spectral#70]
**Chore summary**
The vscode  marketplace still refers to v0.2.4

**Tasks**
- [ ] tag a new release
- [ ] publish on marketplace

**Additional context**
@philsturgeon let us know if we can help

**Comment by philsturgeon** [comment]
@nulltoken can you help us out here? I haven’t learned the release process here yet.

**Comment by nulltoken** [comment]
@philsturgeon Of course. The process is pretty simple.
- Create a PR which updates the changelog and bumps the `version` attribute of  `package.json` (eg. `0.2.5`) 
- When the PR is merged, locally create a tag starting with a `v` (eg. `v0.2.5`) then push it. This will trigger the [release](https://github.com/stoplightio/vscode-spectral/blob/master/.github/workflows/release.yml) workflow that will eventually publish the new VSCode extension version.

**Comment by philsturgeon** [comment]
@nulltoken Thank you! Done. I'll get this back over to semantic-release like some of our other libraries, but this was easy thanks to your instructions. 

@ioggstream "Your extension will live at https://marketplace.visualstudio.com/items?itemName=stoplight.spectral (might take a few minutes for it to show up)."

**Comment by ioggstream** [comment]
Thanks @nulltoken and @philsturgeon ! Great work!
