### ISSUE TITLE
New paths feature from 5.8 not showing in VSCode

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/vscode-spectral#76]
I am running Spectral 5.8.1 locally and absolutely love the new Paths feature!
I am running 0.2.5 of the VSCode extension but not seeing the paths in the problems
![image](https://user-images.githubusercontent.com/25430683/108875638-4d584580-75f5-11eb-8dd6-9e86d064d79e.png)

To reproduce, remove a description from a path and you should see the error misses the path in the VSCode extension.

**Comment by philsturgeon** [comment]
Give https://github.com/stoplightio/vscode-spectral/releases/tag/v1.0.0 a try, should sort that right out!

**Comment by savage-alex** [comment]
Hi,
Given the following bad example:
![image](https://user-images.githubusercontent.com/25430683/172549235-5a15f79e-2ae5-4956-b308-e87d005c5561.png)

I can see the path being returned in the cli 
![image](https://user-images.githubusercontent.com/25430683/172549271-ae798b8c-33dc-4893-bf74-0fc7da99c69a.png)

but within the problems list it remains without the path
![image](https://user-images.githubusercontent.com/25430683/172549330-7e196135-b99c-4731-9ccd-011b045c12d2.png)

Am running 1.0.0 of the extension 
![image](https://user-images.githubusercontent.com/25430683/172549439-9e29db2c-cb29-41a1-82f1-a28783b29ea5.png)

Happy to show / help reproduce if it helps

**Comment by philsturgeon** [comment]
Ah of course, sorry. 

Do you actually want to see the path, or do you want to be able to open the file up at the right point to work on it?

is there a use case I’m not thinking of?
