### ISSUE TITLE
Update to spectral@5.9.0

### ISSUE THREAD

**Issue by exoszajzbuk** [stoplightio/vscode-spectral#85]
Can you please release a new version with the `spectral` dependency updated to the newly released 5.9.0?

**Comment by P0lip** [comment]
Hey, apologies for dropping a ball here.
I'll try to see what we can do about this one.

@mnaumanali94 should we get this scheduled?

**Comment by mnaumanali94** [comment]
Yes. Lets move it to 6.0

**Comment by mnaumanali94** [comment]
Ref: #107
