### ISSUE TITLE
Support different rulesets for different file types within the same workspace

### ISSUE THREAD

**Issue by ahochsteger** [stoplightio/vscode-spectral#89]
**User story.**
As a developer, I can configure multiple rulesets for different file patterns, so that I can validate multiple YAML-based file types within the same workspace.

**Is your feature request related to a problem?**
Currently it's just possible to define one ruleset file for a workspace.
Since we have multiple YAML-based file types within a workspace that all should be validated using different rule sets we have to decide for one primary file type that is linted but the others won't wor.

**Describe the solution you'd like**
A list of rule types mapped to a list of file patterns would solve that problem.

**Comment by philsturgeon** [comment]
Thank for filing this, it's something I want too. It'll be handled by https://github.com/stoplightio/spectral/issues/1021 when we get time to work on that.
